CHANNELS = {
    '电影': {
        '全部': '/vodshow/1/by/hits/page/',
        '喜剧': '/vodshow/1/by/hits/class/喜剧/page/',
        '爱情': '/vodshow/1/by/hits/class/爱情/page/',
        '动作': '/vodshow/1/by/hits/class/动作/page/',
        '科幻': '/vodshow/1/by/hits/class/科幻/page/',
        '恐怖': '/vodshow/1/by/hits/class/恐怖/page/',
        '战争': '/vodshow/1/by/hits/class/战争/page/',
        '剧情': '/vodshow/1/by/hits/class/剧情/page/',
        '悬疑': '/vodshow/1/by/hits/class/悬疑/page/',
        '惊悚': '/vodshow/1/by/hits/class/惊悚/page/',
        '奇幻': '/vodshow/1/by/hits/class/奇幻/page/',
        '冒险': '/vodshow/1/by/hits/class/冒险/page/',
        '动画': '/vodshow/1/by/hits/class/动画/page/',
        '犯罪': '/vodshow/1/by/hits/class/犯罪/page/',
        '儿童': '/vodshow/1/by/hits/class/儿童/page/',
        '经典': '/vodshow/1/by/hits/class/经典/page/',
        '武侠': '/vodshow/1/by/hits/class/武侠/page/',
    },
    '剧集': {
        '全部': '/vodshow/2/by/hits/page/',
        '国产': '/vodshow/2/by/hits/class/国产/page/',
        '港剧': '/vodshow/2/by/hits/class/港剧/page/',
        '日剧': '/vodshow/2/by/hits/class/日剧/page/',
        '欧美': '/vodshow/2/by/hits/class/欧美/page/',
        '韩剧': '/vodshow/2/by/hits/class/韩剧/page/',
    },
    '动漫': {
        '全部': '/vodshow/4/by/hits/page/',
        '日韩动漫': '/vodshow/4/by/hits/class/日韩动漫/page/',
        '欧美动漫': '/vodshow/4/by/hits/class/欧美动漫/page/',
        '国产动漫': '/vodshow/4/by/hits/class/国产动漫/page/',
        '其他动漫': '/vodshow/4/by/hits/class/其他动漫/page/',
        '港台动漫': '/vodshow/4/by/hits/class/港台动漫/page/',
    },
    '综艺': {
        '全部': '/vodshow/3/by/hits/page/',
        '大陆综艺': '/vodshow/3/by/hits/class/大陆综艺/page/',
        '港台综艺': '/vodshow/3/by/hits/class/港台综艺/page/',
        '欧美综艺': '/vodshow/3/by/hits/class/欧美综艺/page/',
        '日韩综艺': '/vodshow/3/by/hits/class/日韩综艺/page/',
    },
    '直播': '/vodshow/6/by/hits.html'
}
